#!/usr/bin/env bash
# Downloads Diablo / Diablo: Hellfire sprite sheets from spriters-resource.com
# Usage: bash script/download_assets.sh

set -euo pipefail

BASE_URL="https://www.spriters-resource.com"
ASSET_DIR="app/assets/sprites"
DELAY=2  # seconds between requests to be polite

download_asset() {
  local id="$1"
  local dir="$2"
  local name="$3"
  local safe_name
  safe_name=$(echo "$name" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/_/g' | sed 's/__*/_/g' | sed 's/^_//;s/_$//')
  local outfile="${ASSET_DIR}/${dir}/${safe_name}.png"

  if [[ -f "$outfile" ]]; then
    echo "SKIP: $outfile already exists"
    return 0
  fi

  # Fetch the asset page to find the actual download URL
  local page
  page=$(curl -sL -A "Mozilla/5.0" "${BASE_URL}/pc_computer/diablodiablohellfire/asset/${id}/")

  # Extract the download link from the page
  local download_path
  download_path=$(echo "$page" | grep -oP '/media/assets/\d+/'"${id}"'\.png(\?[^"'"'"'\s)]+)?' | head -1)

  if [[ -z "$download_path" ]]; then
    echo "FAIL: Could not find download link for ${name} (ID: ${id})"
    return 1
  fi

  echo "Downloading: ${name} -> ${outfile}"
  curl -sL -A "Mozilla/5.0" -o "$outfile" "${BASE_URL}${download_path}"

  if [[ -f "$outfile" ]] && [[ $(stat -c%s "$outfile" 2>/dev/null || stat -f%z "$outfile" 2>/dev/null) -gt 100 ]]; then
    echo "  OK: $(du -h "$outfile" | cut -f1)"
  else
    echo "  WARN: File may be empty or too small"
    rm -f "$outfile"
    return 1
  fi

  sleep "$DELAY"
}

echo "=== Downloading Diablo/Hellfire Sprite Assets ==="
echo ""

# Tiles (most important for map rendering)
echo "--- Tiles ---"
download_asset 68416 tiles "Catacombs"
download_asset 57611 tiles "Cave"
download_asset 57609 tiles "Church Dungeon"
download_asset 63724 tiles "Demon Crypt"
download_asset 60432 tiles "Hell"
download_asset 64339 tiles "Nest"

# Warrior
echo "--- Warrior ---"
download_asset 65404 warrior "Warrior Heavy Armor Weaponless"
download_asset 65426 warrior "Warrior Heavy Armor Axe"
download_asset 65453 warrior "Warrior Heavy Armor Mace"
download_asset 65414 warrior "Warrior Heavy Armor Mace Shield"
download_asset 65415 warrior "Warrior Heavy Armor Shield"
download_asset 65422 warrior "Warrior Heavy Armor Staff"
download_asset 65451 warrior "Warrior Heavy Armor Sword"
download_asset 65416 warrior "Warrior Heavy Armor Sword Shield"
download_asset 65424 warrior "Warrior Heavy Armor Two Maces"
download_asset 65425 warrior "Warrior Heavy Armor Two Swords"
download_asset 65452 warrior "Warrior Light Armor Weaponless"
download_asset 65609 warrior "Warrior Light Armor Axe"
download_asset 65987 warrior "Warrior Light Armor Mace"
download_asset 65953 warrior "Warrior Light Armor Mace Shield"
download_asset 67212 warrior "Warrior Light Armor Shield"
download_asset 66135 warrior "Warrior Light Armor Staff"
download_asset 67292 warrior "Warrior Light Armor Sword"
download_asset 65939 warrior "Warrior Light Armor Sword Shield"
download_asset 65960 warrior "Warrior Light Armor Two Maces"
download_asset 67221 warrior "Warrior Light Armor Two Swords"
download_asset 67260 warrior "Warrior Medium Armor Weaponless"
download_asset 67211 warrior "Warrior Medium Armor Axe"
download_asset 67418 warrior "Warrior Medium Armor Mace"
download_asset 67238 warrior "Warrior Medium Armor Mace Shield"
download_asset 67290 warrior "Warrior Medium Armor Shield"
download_asset 67291 warrior "Warrior Medium Armor Staff"
download_asset 67289 warrior "Warrior Medium Armor Sword"
download_asset 67419 warrior "Warrior Medium Armor Sword2"
download_asset 67261 warrior "Warrior Medium Armor Sword Shield"
download_asset 67213 warrior "Warrior Medium Armor Two Maces"

# Rogue
echo "--- Rogue ---"
download_asset 64215 rogue "Rogue Heavy Armor Weaponless"
download_asset 62947 rogue "Rogue Heavy Armor Axe"
download_asset 63270 rogue "Rogue Heavy Armor Bow"
download_asset 64196 rogue "Rogue Heavy Armor Mace"
download_asset 64070 rogue "Rogue Heavy Armor Mace Shield"
download_asset 64312 rogue "Rogue Heavy Armor Shield"
download_asset 64264 rogue "Rogue Heavy Armor Staff"
download_asset 64240 rogue "Rogue Heavy Armor Sword"
download_asset 64032 rogue "Rogue Heavy Armor Sword Shield"
download_asset 65072 rogue "Rogue Heavy Armor Two Swords"
download_asset 64327 rogue "Rogue Light Armor Weaponless"
download_asset 64340 rogue "Rogue Light Armor Axe"
download_asset 65070 rogue "Rogue Light Armor Bow"
download_asset 65093 rogue "Rogue Light Armor Mace"
download_asset 65094 rogue "Rogue Light Armor Mace Shield"
download_asset 65162 rogue "Rogue Light Armor Shield"
download_asset 65104 rogue "Rogue Light Armor Staff"
download_asset 65186 rogue "Rogue Light Armor Sword"
download_asset 65071 rogue "Rogue Light Armor Sword Shield"
download_asset 65164 rogue "Rogue Light Armor Two Swords"
download_asset 65161 rogue "Rogue Medium Armor Weaponless"
download_asset 65406 rogue "Rogue Medium Armor Axe"
download_asset 65403 rogue "Rogue Medium Armor Bow"
download_asset 65302 rogue "Rogue Medium Armor Mace"
download_asset 65267 rogue "Rogue Medium Armor Mace Shield"
download_asset 65266 rogue "Rogue Medium Armor Shield"
download_asset 65276 rogue "Rogue Medium Armor Staff"
download_asset 65315 rogue "Rogue Medium Armor Sword"
download_asset 65203 rogue "Rogue Medium Armor Sword Shield"

# Sorcerer
echo "--- Sorcerer ---"
download_asset 67557 sorcerer "Sorcerer Heavy Armor Weaponless"
download_asset 67632 sorcerer "Sorcerer Heavy Armor Axe"
download_asset 67631 sorcerer "Sorcerer Heavy Armor Bow"
download_asset 67884 sorcerer "Sorcerer Heavy Armor Mace"
download_asset 67694 sorcerer "Sorcerer Heavy Armor Mace Shield"
download_asset 67920 sorcerer "Sorcerer Heavy Armor Shield"
download_asset 67821 sorcerer "Sorcerer Heavy Armor Staff"
download_asset 67885 sorcerer "Sorcerer Heavy Armor Sword"
download_asset 67693 sorcerer "Sorcerer Heavy Armor Sword Shield"
download_asset 68229 sorcerer "Sorcerer Light Armor Weaponless"
download_asset 68230 sorcerer "Sorcerer Light Armor Axe"
download_asset 68401 sorcerer "Sorcerer Light Armor Bow"
download_asset 68403 sorcerer "Sorcerer Light Armor Mace"
download_asset 68402 sorcerer "Sorcerer Light Armor Mace Shield"
download_asset 68410 sorcerer "Sorcerer Light Armor Shield"
download_asset 68417 sorcerer "Sorcerer Light Armor Staff"
download_asset 68408 sorcerer "Sorcerer Light Armor Sword"
download_asset 68404 sorcerer "Sorcerer Light Armor Sword Shield"
download_asset 68418 sorcerer "Sorcerer Medium Armor Weaponless"
download_asset 68451 sorcerer "Sorcerer Medium Armor Axe"
download_asset 68449 sorcerer "Sorcerer Medium Armor Bow"
download_asset 68658 sorcerer "Sorcerer Medium Armor Mace"
download_asset 68659 sorcerer "Sorcerer Medium Armor Mace Shield"
download_asset 68660 sorcerer "Sorcerer Medium Armor Shield"
download_asset 68450 sorcerer "Sorcerer Medium Armor Staff"
download_asset 68661 sorcerer "Sorcerer Medium Armor Sword"
download_asset 68662 sorcerer "Sorcerer Medium Armor Sword Shield"

# Monk
echo "--- Monk ---"
download_asset 60062 monk "Monk Heavy Armor Weaponless"
download_asset 59265 monk "Monk Heavy Armor Axe"
download_asset 59271 monk "Monk Heavy Armor Bow"
download_asset 59536 monk "Monk Heavy Armor Mace"
download_asset 59479 monk "Monk Heavy Armor Mace Shield"
download_asset 60006 monk "Monk Heavy Armor Shield"
download_asset 60005 monk "Monk Heavy Armor Staff"
download_asset 60059 monk "Monk Heavy Armor Sword"
download_asset 59351 monk "Monk Heavy Armor Sword Shield"
download_asset 60279 monk "Monk Light Armor Weaponless"
download_asset 60114 monk "Monk Light Armor Axe"
download_asset 60128 monk "Monk Light Armor Bow"
download_asset 60278 monk "Monk Light Armor Mace"
download_asset 60252 monk "Monk Light Armor Mace Shield"
download_asset 60303 monk "Monk Light Armor Shield"
download_asset 60304 monk "Monk Light Armor Staff"
download_asset 60574 monk "Monk Light Armor Sword"
download_asset 60247 monk "Monk Light Armor Sword Shield"
download_asset 62948 monk "Monk Medium Armor Weaponless"
download_asset 60245 monk "Monk Medium Armor Axe"
download_asset 60302 monk "Monk Medium Armor Bow"
download_asset 62949 monk "Monk Medium Armor Mace"
download_asset 60349 monk "Monk Medium Armor Mace Shield"
download_asset 62959 monk "Monk Medium Armor Shield"
download_asset 62960 monk "Monk Medium Armor Staff"
download_asset 62961 monk "Monk Medium Armor Sword"
download_asset 60312 monk "Monk Medium Armor Sword Shield"

# NPCs
echo "--- NPCs ---"
download_asset 57608 npcs "Cow"
download_asset 64234 npcs "Priest and Butch"
download_asset 55265 npcs "Townsfolk"
download_asset 59274 npcs "Townsfolk Hellfire"

# Enemies & Bosses
echo "--- Enemies & Bosses ---"
download_asset 52929 enemies "Azid"
download_asset 58787 enemies "Balrog"
download_asset 52930 enemies "Bat"
download_asset 57993 enemies "Big Fallen Ones Mace"
download_asset 55428 enemies "Black Knight"
download_asset 57819 enemies "The Butcher"
download_asset 57625 enemies "Dark Mage"
download_asset 57466 enemies "Diablo"
download_asset 57821 enemies "Fallen One Sword"
download_asset 57336 enemies "Fallen Ones Spear"
download_asset 58011 enemies "Felltwin"
download_asset 57842 enemies "Fireman"
download_asset 57843 enemies "Gargoyle"
download_asset 57994 enemies "Goatman Lord"
download_asset 57844 enemies "Goatman Bow"
download_asset 57846 enemies "Goatman Mace"
download_asset 57845 enemies "Golem"
download_asset 57983 enemies "Hidden"
download_asset 57951 enemies "Mage"
download_asset 57974 enemies "Magma Demon"
download_asset 57820 enemies "Overlord"
download_asset 58053 enemies "Rhino Demon"
download_asset 57984 enemies "Scavenger"
download_asset 58026 enemies "Shredded"
download_asset 68655 enemies "Skeleton Demon"
download_asset 68656 enemies "Skeleton King"
download_asset 68653 enemies "Skeleton Bow"
download_asset 68657 enemies "Skeleton Sword Shield"
download_asset 68652 enemies "Skeleton Two Axes"
download_asset 57985 enemies "Stormrider"
download_asset 56431 enemies "Succubus"
download_asset 57982 enemies "Viper"
download_asset 57981 enemies "Zombie"

# Enemies & Bosses (Hellfire)
echo "--- Enemies & Bosses (Hellfire) ---"
download_asset 62891 enemies_hellfire "Ant Worm"
download_asset 59264 enemies_hellfire "Byclops"
download_asset 59259 enemies_hellfire "Crypt Demon"
download_asset 59206 enemies_hellfire "Dark Spider"
download_asset 59200 enemies_hellfire "Defiler"
download_asset 59342 enemies_hellfire "Firebat"
download_asset 59346 enemies_hellfire "Flesh Think"
download_asset 68654 enemies_hellfire "Ghost"
download_asset 59340 enemies_hellfire "Gravedigger"
download_asset 59341 enemies_hellfire "Hellbat"
download_asset 59339 enemies_hellfire "Hellboar"
download_asset 59338 enemies_hellfire "Hork Demon"
download_asset 59186 enemies_hellfire "Lash Worm"
download_asset 59337 enemies_hellfire "Lich"
download_asset 59336 enemies_hellfire "Na-Krul"
download_asset 59293 enemies_hellfire "Necromorb"
download_asset 59270 enemies_hellfire "Psychorb"
download_asset 59335 enemies_hellfire "Reaper"
download_asset 59334 enemies_hellfire "Stringer"
download_asset 59333 enemies_hellfire "Tom Rat"
download_asset 59332 enemies_hellfire "Venomtail"

# Effects
echo "--- Effects ---"
download_asset 96094 effects "Acid Effects"
download_asset 97919 effects "Arrow"
download_asset 96439 effects "Blue Explosion"
download_asset 96404 effects "Bone Animation"
download_asset 96481 effects "Defense Buff"
download_asset 96433 effects "Doom Serpents"
download_asset 97918 effects "Explosion1"
download_asset 96356 effects "Explosion2"
download_asset 96995 effects "Fire Arrow"
download_asset 96403 effects "Fire Explosion"
download_asset 96994 effects "Fireball1"
download_asset 96400 effects "Fireball2"
download_asset 97250 effects "Fireman Run"
download_asset 97249 effects "Firewall"
download_asset 97924 effects "Flame"
download_asset 97917 effects "Flare Blue"
download_asset 97923 effects "Flare Red"
download_asset 97916 effects "Flare Yellow"
download_asset 96402 effects "Ghost Attack"
download_asset 96434 effects "Greater Rune of Fire"
download_asset 96437 effects "Guardian"
download_asset 97922 effects "Holy Bolt1"
download_asset 96399 effects "Holy Bolt2"
download_asset 97921 effects "Inferno"
download_asset 96435 effects "King Die"
download_asset 96438 effects "Light Source"
download_asset 96436 effects "Lightning"
download_asset 97915 effects "Lightning Arrow"
download_asset 96397 effects "Magic Missile Blue"
download_asset 96396 effects "Magic Missile Red"
download_asset 96398 effects "Magic Missile White"
download_asset 96395 effects "Magic Missile Yellow"
download_asset 97914 effects "Magma Ball"
download_asset 97248 effects "Metal Hit"
download_asset 96355 effects "Na-Krul Missile"
download_asset 96354 effects "Portals"
download_asset 96353 effects "Succubus Missile Blue"

# Miscellaneous
echo "--- Miscellaneous ---"
download_asset 62208 miscellaneous "Cursors"
download_asset 110114 miscellaneous "Diablo Logo"
download_asset 68705 miscellaneous "Equipment Damage Icons"
download_asset 68706 miscellaneous "Font"
download_asset 96401 miscellaneous "Hero Art"
download_asset 96394 miscellaneous "HUD"
download_asset 58058 miscellaneous "In Game Items"
download_asset 63052 miscellaneous "Ingame Items Hellfire"
download_asset 59437 miscellaneous "Items"
download_asset 97920 miscellaneous "Loading Images"
download_asset 63251 miscellaneous "Map Hellfire"
download_asset 68707 miscellaneous "Menus"
download_asset 55264 miscellaneous "Objects"
download_asset 63252 miscellaneous "Objects Hellfire"
download_asset 68735 miscellaneous "Pentagram"
download_asset 68666 miscellaneous "Player Inventory Menu"
download_asset 68667 miscellaneous "Spell Icons"

echo ""
echo "=== Download complete ==="
echo "Total files:"
find "$ASSET_DIR" -name "*.png" | wc -l
